apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-site-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-site-app
  template:
    metadata:
      labels:
        app: web-site-app
    spec:
      containers:
      - name: web-site-app
        image: igogo/devops-learning-warsaw:v0.0.1
